name: skylinq
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  bloc: ^8.0.1
  build_runner: ^2.4.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_serializable: ^6.8.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  syncfusion_flutter_gauges: ^25.2.3
  syncfusion_flutter_sliders: ^25.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
